### ISSUE TITLE
Сделать регистрацию пользователя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#1]
В приложении может быть зарегистрированный или незарегистрированный пользователь.
Пользователи регистрируются в отдельной группе НГВ
Для того что бы не светить пароль администартора - который может создавать пользователей будет сделан специальный сервис. Сервис должен позволять проверять уникальности логина при регистрации.

При первом входе пользователю предлагается зарегистрироваться (при наличии интернета), при этом следует указать:
- электронную почту (обязательно);
- пароль (обязательно с контролем стойкости);
- ФИО (опционально или обязательно?)
- телефон (опционально и поле должно на смартфонах заполняться автоматом, а на планшетах не показываться);
- район (регион) для скачивания данных для оффлайн работы приложения (список районов (регионов) должен получаться с сервера).
Пользователь должен мочь сменить пароль, а также изменить район (регион) для оффлайн работы. Почту (логин) менять нельзя. Для смены почты необходимо зарегистрироваться заново.
Пользователь может отказаться от регистрации. Тогда необходимо запросить район (регион) для оффланй работы. 
Согласно выбранному району (региону) выполнятся предварительное скачивание (по аналогии с лесным инспектором):
- лесохозяйственное деление;
- космосъемка с Landsat из Геомиксера;
- подложка от Сканэкс.

**Comment by BishopGIS** [comment]
Сервис регистрации пользователей имеется. см. nextgis/nextgisweb_forest_violations#12
Протестирован работает. 
Код формирования ссылки надо вот сюда поместить https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/util/NGWUtil.java#L55
а сам запрос стандартный https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/util/NetworkUtil.java#L198

**Comment by 4eRTuk** [comment]
Fix in edc146f9befe3f0ff8bec02928f092e2591f71b9

See #8 also.
