### ISSUE TITLE
При переустановке программы запрашивать район работы

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#11]
Сейчас район хранится в конфиге, а запрос появляется только если аккаунт не создан. если переустановить порграмму район удаляется, а аккаунт - нет. И при запуспе программы район устанваливается в координаты -2000,-2000, 2000, 2000.
Надо перезапрашивать район - диалог при старте и перекачивать данные для оффдайн работы.

**Comment by 4eRTuk** [comment]
Сейчас после переустановки насколько я понимаю район берется из конфига аккаунта и данные просто перекачиваются. Может быть вынести смену района в настройки?

**Comment by BishopGIS** [comment]
Да, разумеется. То было временное решение.
