### ISSUE TITLE
При выборе ориентировки клавиатура закрывает поле ввода

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#19]
![screenshot_2015-11-11-16-34-46](https://cloud.githubusercontent.com/assets/1708122/11092238/acbdbf88-8892-11e5-91d0-a15962ade441.png).
В идеале поджимать размер активити, если нельзя - то поле и индикацию угда поворота - перенести вверх.

**Comment by BishopGIS** [comment]
Еще мы договаривались, что отметка о применении будет не в панели инструментов, а в FAB

**Comment by 4eRTuk** [comment]
Это стандартная клавиатура?
