### ISSUE TITLE
Поменять диалог ввода информации

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#21]
Сейчас имеется 3 большие кнопки. И много пустого места.
Предлагаю все что ниже поля ввода текста сделать картой. Ввод координат повесить на FAB с меню. При открытии активити сразу ставить точку на карту в текущем местоположении и выводить "хваталку", что бы ее можно было сдвинуть.
Еще как вариант - на ФАБ повесить отправку, а кнопки фото, текущее местоположение, ориентировка вынести в тулбар

**Comment by 4eRTuk** [comment]
Может селать три маленьких ФАБа внизу по центру карты (вверху по границе с текстовым полем?) - фото, текущее, по компасу. А большую ФАБ для отправки сообщения поместить справа в поле для текста сообщения?

**Comment by BishopGIS** [comment]
Давай так.

**Comment by 4eRTuk** [comment]
что-то типа такого
https://www.dropbox.com/s/s5cupzfpvesol5e/2016-01-14%2016.47.51.png?dl=0

**Comment by BishopGIS** [comment]
Да, только поле ввода перенести вверх карты, что бы клавиатура не перекрывала.

**Comment by 4eRTuk** [comment]
Клавиатура же смещает экран вверх. К тому же по-моему логичнее текстовое поле внизу, так во всех мессенджерах сделано.
https://www.dropbox.com/s/6m4ie91d6tw29sq/2016-01-15%2008.20.37.png?dl=0

**Comment by BishopGIS** [comment]
Ну давай так
