### ISSUE TITLE
В диалоге ввода контактных данных нет кнопки отмена

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#22]
Еще нужен текст над элементами:
"Укажите ваши контактные данные, чтобы с вами мог связаться диспетчер (фамилия, имя и телефон - обязательно)"

**Comment by NikitaFeodonit** [comment]
Поправлю:
"Укажите ваши контактные данные, чтобы с вами мог связаться диспетчер (фамилия, имя и телефон - обязательно)"

**Comment by 4eRTuk** [comment]
Сейчас есть отдельное поле для почты и поле для ФИО вместе с телефоном. Может стоит вынести телефон в отдельное поле?

**Comment by BishopGIS** [comment]
Да, так бы было удобнее.
