### ISSUE TITLE
Заголовок активити "Лесозаготовка" слишком официален

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#23]
Предлагаю назвать "Сообщить о проблеме леса"

**Comment by 4eRTuk** [comment]
Может просто "вырубка"? А то "...о проблеме леса" еще страннее звучит, тогда уж "...о проблеме в лесу".

**Comment by BishopGIS** [comment]
Незаконная рубка - так ок?
