### ISSUE TITLE
Нужна иконка в виде флажка при постановке точки на карту

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#25]
Например:
http://romannurik.github.io/AndroidAssetStudio/icons-actionbar.html#source.type=clipart&source.space.trim=0&source.space.pad=0&source.clipart=res%2Fclipart%2Ficons%2Fcontent_flag.svg&name=ic_action_content_flag&theme=light&color=33b5e5%2C60

**Comment by 4eRTuk** [comment]
Не понял, это над хваталкой вместо уветного круга?

**Comment by simgislab** [comment]
а мне нравится как сейчас - неназойливо

**Comment by BishopGIS** [comment]
Ну это же для обычных людей - должно быть как-то няшно чтоли.

**Comment by BishopGIS** [comment]
Пока забьем и оставим как есть.
