### ISSUE TITLE
В активити неверно отображаются координаты

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#28]
Почему-то широта - "не число". Хотя точка была поставлена на карту вручную.

**Comment by 4eRTuk** [comment]
С последними изменениями воспроизводится? Не число - NaN или значения по нулям?

**Comment by BishopGIS** [comment]
Координаты показываются, правда теперь дата как-то странно выглядит.
![screenshot_2016-01-18-12-23-20](https://cloud.githubusercontent.com/assets/1708122/12387472/ce7be480-bddd-11e5-9a41-0561e6c8526b.png)
