### ISSUE TITLE
Не выполняется отправка сообщения

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#29]
Хотя запись и была создана - на сервере она не появилась, даже с ручным запуском синхронизации. Возможно из-за #28

**Comment by 4eRTuk** [comment]
Теперь должна появляться.

**Comment by BishopGIS** [comment]
У меня опять не отправляются сообщения.

**Comment by BishopGIS** [comment]
Отправляются.
