### ISSUE TITLE
Сделать фильтрацию сообщений в списке

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#3]
Показывать определенные сообщения и документы

**Comment by 4eRTuk** [comment]
Имеется ввиду настраиваемую пользователем типа диалога для поиска по сообщениям?

**Comment by BishopGIS** [comment]
Нет. Посмотри как сделано в инспекторе:

* в тулбаре появилась кнопка фильтра, открывающая контекстное меню с чекбоксами
* можно фильтровать показ - только сообщения о пожарах, только сообщения о рубках. Ну или все вместе. 

Еще у нас показываются сообщения не старше полугода.
