### ISSUE TITLE
В списке сообщений сделать кнопку - посмотреть на карте

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#32]
При клике переход к вкладке карты и приближение к точке сообщения

**Comment by 4eRTuk** [comment]
Прямо из списка или из окна просмотра сообщения?

**Comment by BishopGIS** [comment]
Я думал из списка. Но у нас на клик висит уже просмотр деталей, может длинный тап?

**Comment by 4eRTuk** [comment]
Повесил на длинный тап пока что.
