### ISSUE TITLE
Зависание интерфейса при запуске

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#34]
После запуска программы появляется главное окно. Записи в списко добавляются только через 40-60 секунд (причем запись всего одна!)

**Comment by 4eRTuk** [comment]
Какое устройство? Не могу воспроизвести.

**Comment by BishopGIS** [comment]
Довольно мощное - Galaxy Note 8. Скорее всего вот из-за этого nextgis/mobile.forestviolate.inspector#60

**Comment by 4eRTuk** [comment]
Не, программа сама долго загружается и интерфейс виснет при запуске. Список тут ни при чем.

**Comment by BishopGIS** [comment]
А в лесном инспекторе, где в 3 раза больше слоев такого не просиходит. Архитектурно программы похожи.
