### ISSUE TITLE
Переместить точку в центр экрана

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#38]
Я хотел поставить точку. Открывается карта, появляется точка с "хваталкой". Потом нажал ввести через компас. Точка улетела в Москву. Теперь ее обратно на Дальний восток проблематичено пододвинуть. Нужна кнопка переместить точку в центр экрана.

**Comment by 4eRTuk** [comment]
Насколько это реальный случай? Ведь предполагается, что пользователь будет вводить данные непосредственно в поле.

**Comment by BishopGIS** [comment]
Я думаю вполне реальный. Ну приехал из города. ГПС не подхватился еще. Вот его и уносит в тот же Владивосток. Потом либо зумится либо еще как-то. Да на панель тулбара вынести кнопку - этого достаточно.
