### ISSUE TITLE
Сделать разные иконки на карте

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#42]
Разные иконки для точек пожар/рубка
Разные иконки свое сообщение/сообщение других пользователей (разный цвет)
Отдельная иконка для точек лесонарушений (оставляем красные кружки).

**Comment by 4eRTuk** [comment]
Еще и для мусор/прочее видимо?

**Comment by BishopGIS** [comment]
Да, можно и так.
