### ISSUE TITLE
Добавить 2 новых типа сообщения пользователя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#43]
1. Замусоривание
2. Прочее

**Comment by 4eRTuk** [comment]
Предлагаю вынести выбор типа в тулбар в окне ввода сообщения, а то в раскрывающемся FAB слишком много кнопок. И оставить только одну большую FAB кнопку на главном экране. Звонок диспетчеру в тулбар тоже как иконка.

**Comment by BishopGIS** [comment]
Оставляем как есть - утверждено Заказчиком.

**Comment by 4eRTuk** [comment]
А какой период актуальности для этих типов? Две недели?

**Comment by BishopGIS** [comment]
Давай 30 дней
