### ISSUE TITLE
В поле mtype писать текст

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#44]
1. Лесной пожар
2. Незаконная рубка леса
3. Мусор в лесу
4. Прочее

**Comment by 4eRTuk** [comment]
Может добавить словарь по внешнему ключу? А то при локализации будет каша. Или только русский нужен?

**Comment by BishopGIS** [comment]
Ну у нас так и было - понятные цифровые идентификаторы. Просто внешней системе, которая данные забирает, лень преобразовывать их в текст. Поэтому пиши текст, а проблема каши - проблема внешней системы которая данные забирает.

**Comment by BishopGIS** [comment]
Новая структура слоя будет вот такой nextgis/nextgisweb_forest_violations#21

**Comment by 4eRTuk** [comment]
Можно добавить отдельное текстовое поле для типа? Или целое, если mtype будет изменен на текстовое.

**Comment by BishopGIS** [comment]
Это как тебе удобнее, тогда поменяй тикет, nextgis/nextgisweb_forest_violations#21 что бы там было как надо. Внешней системе нужны определенные поля, если у тебя будет добавка - то ей на это все равно.
