### ISSUE TITLE
Разделить поле contact на имя и телефон

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#45]
Писать ФИО и телефон в разные поля

**Comment by 4eRTuk** [comment]
Нужно отдельное поле и в таблице на сервере в таком случае. Переименовать stmessage может? Сейчас оно никак не используется вроде.

**Comment by BishopGIS** [comment]
Поле stmessage используется. В него пишет диспетчер разную полезную информацию по оповещению. Еще диспетчер меняет статусы.
По поводу полей будет вот так: nextgis/nextgisweb_forest_violations#21
