### ISSUE TITLE
Не выйти из режима ввода фото

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#47]
Нажимаю добавить фото - появляется иконка фото прямо на карте (что не есть хорошо, потому что зеленая иконка на зеленом фоне не видна). Жму на иконку - открываетсч приложение камеры. Добавляю фото - фото появляется рядом с иконкой. Больше ничего сделать нельзя, кроме добавления нового фото. 
При повороте экрана фото исчезает, но если опять на нажать на создать фото - открывается ранее созданные фотки.
![screenshot_2016-03-05-22-41-12](https://cloud.githubusercontent.com/assets/1708122/13549939/a9a5f816-e322-11e5-9abf-0d575924788e.png)

**Comment by 4eRTuk** [comment]
Для завершения есть кнопка ОК с галочкой в тулбаре. Можно перенести влево (от заголовка) или в ФАБ. Какой цвет задать для иконки добавления фото?

**Comment by BishopGIS** [comment]
Она не работает. Тулбар вообще не реагирует на нажатия.
