### ISSUE TITLE
Сделать период актуальности новых сообщений

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#5]
Т.к. данные можно вносить оффлайн, а когда устройство установит связь с сервером неизвестно, предлагается установить для пожара период актуальности данных – 48 часов, а рубки – 15 дней.

**Comment by 4eRTuk** [comment]
По истечению этого срока просто удалять сообщения? Или может выводить диалог "Актуально? Да/нет"?

**Comment by BishopGIS** [comment]
Удалять. А то будет задалбливать, если мого введено.
