### ISSUE TITLE
Поддержка синхронизации для слоя лесонарушений

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#56]
Сделать для слоя лесонарушений nextgis/android_gisapp#345 , т.к. там точек 1500 и больше может быть и все эти точки при каждой синхронизации гоняются туда-сюда, что создает приличный трафик. 

Приоритет самый низкий.

**Comment by 4eRTuk** [comment]
Все слои с `"tracked": true` поддерживаются.
