### ISSUE TITLE
Добавить объясняющий экран

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#63]
По аналогии с nextgis/android_gisapp#8

**Comment by 4eRTuk** [comment]
Как именно? Showcase, tooltips или отдельные экраны-intro со скроллом?

**Comment by BishopGIS** [comment]
@PoohE ответь пожалуйста или уточни, если тебе термины не понятны.

**Comment by PoohE** [comment]
термины не понятны, в инете не нашел, вы могли бы привести примеры для понимания?

**Comment by 4eRTuk** [comment]
@PoohE 
* Showcase - акцентирование внимания на элементе управления. [Пример](https://github.com/deano2390/MaterialShowcaseView)
* Tooltips - всплывающие балуны около элементов управления. [Пример](https://android-arsenal.com/details/1/2526)
* Intro screens - отдельное(-ые) окно(-а) с вводной информацией или инструкциями. [Пример](https://github.com/PaoloRotolo/AppIntro)

**Comment by PoohE** [comment]
хотелось бы следующий сценарий:
при открытии Intro screens обьясняющий как пользоваться
при его закрытии карта с Showcase на нижней кнопке
при нажатии на эту кнопку Tooltips у всех вариантов

**Comment by 4eRTuk** [comment]
В последних коммитах у кнопок есть подписи слева, может не стоит tooltips добавлять? По сути дублирование.

Что написать в intro?

**Comment by PoohE** [comment]
а можно подписи заменить на tooltips чтобы они не все время висели? или оба этих вариантов будет выглядеть одинаково? в чем их принципиальное различие?

**Comment by PoohE** [comment]
intro - текст нужно сформировать, вы можете помочь? дать примеры ?

**Comment by 4eRTuk** [comment]
@PoohE 
Принципиальное - ни в чем. Подписи все время отображаются, подсказки можно сделать только чтобы один раз показывались.

В интро обычно рассказывается о приложении и его функции. Тут все на свое усмотрение.

**Comment by 4eRTuk** [comment]
Можно написать в первом слайде, что это приложение для мониторинга лесонарушений. Во втором как-то замотивировать пользователей самих оставлять через него сообщения. Ну и т.д.

**Comment by PoohE** [comment]
Intro screens: 4 экрана с текстами:
1.  Если вы любите путешествия, рыбалку, охоту -  это  приложение «Сохраним лес» для вас - неравнодушных и мужественных людей,  готовых  протянуть руку помощи природе Дальнего востока России. (можно картинку вставить?)
2.Если вы увидели в лесу пожар, незаконную рубку или несанкционированную свалку - отправьте сообщение (можно картинку кнопки?). Ваш сигнал получат диспетчеры Управления лесного хозяйства и ЛесАвиаОхраны. 
3. Лесные рейнджеры отправятся тушить пожар, задерживать лесных браконьеров или искать виновников свалки. Как только меры будут предприняты, вы тут же узнаете об этом. 
4.Это приложение создано Всемирным фондом дикой природы –WWF России, который охраняет природу Дальнего Востока. Если вам интересно, вы готовы помочь, зайдите к нам: taigastory.ru  (Панда-лейба)

**Comment by PoohE** [comment]
Showcase:
на кнопку +
текст 
Увидел, что лес в беде - нажми на кнопку

**Comment by PoohE** [comment]
Tooltips для кнопок:
Звонок диспетчеру
Нелегальная рубка в лесу
Пожар в лесу
Мусорная свалка в лесу

прочее - убираем

**Comment by PoohE** [comment]
Легенду вынести отдельным окном и разместить ссылку в меню верхний верхний
Легенда:
1.	Твое сообщение
2.	Сообщение других людей
3.	Информация из космоса
4.	Нелегальная рубка в лесу
5.	Лесной пожар
6.	Мусорная свалка в глубине леса

**Comment by PoohE** [comment]
можно ли для приложения использовать иконку типа: 
![4](https://cloud.githubusercontent.com/assets/10294693/15500723/5b839bc0-21ed-11e6-9be1-68a1eb434d84.png)

**Comment by BishopGIS** [comment]
Давай иконку - поменяем. Или эту поставить?

**Comment by PoohE** [comment]
так вот я ее повесил, нужно в другом формате?

**Comment by BishopGIS** [comment]
Такой пойдет. Поменяем.

**Comment by 4eRTuk** [comment]
@PoohE какие картинки вставить в intro screen?

**Comment by 4eRTuk** [comment]
в первое добавил лого, в третье иконку телефона. поменяю если надо.
