### ISSUE TITLE
Убрать прочее

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#65]
Везде убрать прочее

**Comment by 4eRTuk** [comment]
Тип сообщений?

**Comment by BishopGIS** [comment]
Да это тип сообщений, но у нас он проходит:

* кнопка
* в легенде на карте
* собственно значок
* и т.д.

Но из программы не убирай, только из интерфейса пользователя, а то вдруг опять захотят вернуть.

**Comment by 4eRTuk** [comment]
Оставил только в списке сообщений, если вдруг с сервера придут какие-то данные.
