### ISSUE TITLE
Повышенное потребление батареи

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#67]
Варианты:
синхронизация раз в 2 часа
уменьшить количество слоев включенных по-умолчанию при отображении
GPS
возможно какие-то циклы

**Comment by 4eRTuk** [comment]
Это если в фоне? Если при открытом, то думаю основной источник - GPS.

**Comment by BishopGIS** [comment]
@PoohE когда повышенное потребление?

**Comment by PoohE** [comment]
при фоновом висении программы: в среднем батарея которой при других условиях хватает на 12 часов работы разряжается часа за 2-3
при этом приложение не используется просто висит в треше

**Comment by PoohE** [comment]
остановить расход батареи помогает только принудительная остановка и выгрузка приложения

**Comment by 4eRTuk** [comment]
@PoohE наблюдается ли в последней сборке?

**Comment by BishopGIS** [comment]
Опять репортят. Потребление определяют через "свойства-батарея".
Я посмотрел у нас на планшете - там меньше 5% батареи.
Можно добавить каких-то отладочных сообщений, что бы можно было понять что происходит?

**Comment by 4eRTuk** [comment]
А есть хоть какие-то логи с устройства?

**Comment by BishopGIS** [comment]
Больше не воспроизводится.
