### ISSUE TITLE
Добавить подложки

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#69]
Добавить подложки: bing, dark, genshtab, google, kosmosnimki, mapbox, rosreestr, wikimapia если они выдаются тайлами в 3857

**Comment by PoohE** [comment]
могу более подробно написать: там по одной подложке из каждого пула

**Comment by 4eRTuk** [comment]
@PoohE да, желательно с URL-ами

**Comment by PoohE** [comment]
а где их взять? есть список какой нибудь?

**Comment by BishopGIS** [comment]
@PoohE Ну ты их же в браузере открывал - вот и дай хотя бы эти ссылки.

**Comment by PoohE** [comment]
я их открывал в приложении nextgis mob

**Comment by BishopGIS** [comment]
@PoohE Ты о функции "Добавить геосервис"?

**Comment by PoohE** [comment]
да

**Comment by PoohE** [comment]
bing sat, dark matter, esri terrain, genshtab, google hybrid, kosmosnimki map, mapbox sat, osm, opentopomap, osm transport, rosreestr , topomap, wikimapia

**Comment by 4eRTuk** [comment]
Bing sat, topomap, wikimedia - не работают.

**Comment by 4eRTuk** [comment]
Topomap работает на маленьких зумах только, wikimedia все ок. Но бинг все же не работает.

**Comment by PoohE** [comment]
а почему? в советских картах например bing работает, может адресс не тот?


Jamás te rindas, pase lo que pase!
*Pooh*
mailto: down.pooh@gmail.com
telegram: *+79242345445*

2016-05-21 0:13 GMT+10:00 Stanislav Petriakov <notifications@github.com>:

**Comment by BishopGIS** [comment]
У бинга несовместимая схема тайлирования.
23 мая 2016 г. 7:40 пользователь "Pooh" <notifications@github.com> написал:
