### ISSUE TITLE
Сделать список на главном экране

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#7]
В списке отображать сообщения свои и других пользователей, акты от инспекторов.
Отображение должно зависеть от того авторизован пользователь или нет.

**Comment by 4eRTuk** [comment]
Что должно быть отображено для авторизованного пользователя? Дополнительно только статусы?

**Comment by BishopGIS** [comment]
Неавторизованный пользователь не должен видеть статусы чужих сообщений и акты инспекторов.
Акты не смогут еще и потому, что сервер не дает анонимного доступа к этому слою.
