### ISSUE TITLE
Качество картинок первого экрана

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#74]
Первый запуск сопровождается экраном с 4-мя страницами с объяснением как пользоваться программой. 3 страницы из 4-х имеют картинки низкого качества, что выглядит неинформативно и некрасиво.

![screenshot_2016-06-12-20-07-20](https://cloud.githubusercontent.com/assets/1708122/15992404/424a856c-30dc-11e6-85ca-8f5df0434ed3.png)

![screenshot_2016-06-12-20-07-34](https://cloud.githubusercontent.com/assets/1708122/15992406/4998fce0-30dc-11e6-991b-5133a1b72bc2.png)

![screenshot_2016-06-12-20-08-09](https://cloud.githubusercontent.com/assets/1708122/15992408/4d702fbe-30dc-11e6-8ed1-15a03b40ac9d.png)

Как минимум картинки должны растягиваться таким образом, что бы не вылезать за границу экрана. Т.е. должна учитываться ширина и высота. Кроме того, необходимо ввести ограничение - 90-85% от площади. Т.е. marging 5-7% от краев.

**Comment by 4eRTuk** [comment]
Какие именно картинки вставить? Можно скинуть их?

**Comment by BishopGIS** [comment]
Для первого экрана была качественная картинка:
https://cloud.githubusercontent.com/assets/10294693/15500723/5b839bc0-21ed-11e6-9be1-68a1eb434d84.png
Для трубки - можно найти svg и сгенерить нужного размера png. Например https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_settings_phone_black_24px.svg (https://design.google.com/icons)
Для заключительный - https://en.wikipedia.org/wiki/File:WWF_logo.svg
