### ISSUE TITLE
При первоначальной загрузке подгружаются не все сообщения

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#77]
Сейчас сообщений более 50, но подгрузилось не более 10.
Возможно сработал фильтр что бы не отображать старые, но тогда откуда взялось сообщение от 1.1.1970? И почему тогда этот фильтр не сработал на акты от инспекторов?

![screenshot_2016-06-12-20-30-31](https://cloud.githubusercontent.com/assets/1708122/15992454/eec4c018-30dd-11e6-8ea3-22c07379fb55.png)

**Comment by 4eRTuk** [comment]
Так тут сработал bbox скорее всего для выбранного района. Или нужно вообще все сообщения загружать?

**Comment by BishopGIS** [comment]
Нет, подгрузка с учетом bbox это верно. 
Проверю для Хабаровского края. Если подгрузятся - тогда закрою.

**Comment by BishopGIS** [comment]
Я посмотрел сообщения. Да, гораздо меньше, но все равно не совпадает количество. Проверь, может там как-то фильтры накладываются. Если нет по дате ограничений должно быть 8 или более (8 это все что попадает в границу) по bbox - может быть больше.
![2016-06-13 22-50-15](https://cloud.githubusercontent.com/assets/1708122/16021089/e2c74030-31c1-11e6-91f1-f506c4381a19.png)

**Comment by 4eRTuk** [comment]
Подебажил еще раз более подробно - все ок. Учитывая фильтр по дате и bbox, запрос посылается такой: http://176.9.38.120/fv/api/resource/83/feature/?mdate={%22gt%22:%222016-01-04T00:00:00Z%22}&bbox=14516073.000000,5204969.000000,15477032.000000,6184456.000000

Возвращается 14 фич, вроде бы все верно.

**Comment by BishopGIS** [comment]
Да, главное что бы быльше 8 было.
