### ISSUE TITLE
Не сохраняются координаты точки

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#78]
Создал пару точек (рубка и пожар) все кроме координат сохранилось.

http://176.9.38.120/fv/api/resource/83/feature/72
http://176.9.38.120/fv/api/resource/83/feature/73

![screenshot_2016-06-12-20-26-38](https://cloud.githubusercontent.com/assets/1708122/15992459/204ba25a-30de-11e6-9ca1-3936f1474b4f.png)

Фильтр на сервере точно не причем. Вот тоже для администратора:
http://176.9.38.120/fv/api/resource/64/feature/72
http://176.9.38.120/fv/api/resource/64/feature/73

**Comment by 4eRTuk** [comment]
Для тестовой версии координаты передаются нулевые:
> `if (com.nextgis.maplib.util.Constants.DEBUG_MODE) {
                pt = new GeoPoint(0, 0);
            } 
`

Оставить или убрать?

**Comment by BishopGIS** [comment]
Конечно убираем. Сейчас же точку можно сдвинуть куда надо руками.
