### ISSUE TITLE
Выбор сервера для приема лесонарушений 

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#81]
Развертывание системы предполагает несколько адресов серверов для приема сообщений. Мобильное приложение не должно спрашивать у пользователя адрес сервера куда будут уходить лесонарушения.
Предлагается, создать единую точку входа при первоначальной настройки, откуда будут браться необходимые данные.
Так как у нас уже есть выбор региона, то правильнее как раз видоизменить логику в этом месте.
Предварительно по адресу: http://176.9.38.120/fvstatic/reg.geojson размещены данные по охвату, телефону диспетчера. Я туда добавил поле url где и содержится адрес сервера лесонарушений.

Мобильное при первом запуске должно получать этот файл и выводить диалог:
![screenshot_2016-06-12-20-11-06](https://cloud.githubusercontent.com/assets/1708122/16022200/b9980c16-31c7-11e6-919b-cff91284b826.png)
 
Тамже должен получаться сервер. Далее все общение уже идет с этим конкретным сервером.

**Comment by 4eRTuk** [comment]
А экран регистрации/авторизации как в этом случае отображать?

**Comment by BishopGIS** [comment]
Да, тут надо порядок сменить:
1. Вначале выбор региона/сервера
2. Регистрация (опционально)
3. Первоначальная установка.
