### ISSUE TITLE
Не отправляются сообщения незарегистрированного пользователя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#84]
Если пользователь не зарегистрирован, то в рамках синхронизации происходит обмен данными с сервером. Причем вначале получаются данные с сервера, а потом передаются на сервер. 
Незарегистрированный пользователь не имеет доступа к актам инспекторов. В результате получает ошибку 401. Видимо на этом весь процесс прерывается не доходя до отправки сообщения пользователя на сервер.

Решение: Ошибка синхронизации одного слоя не должно прерывать процесс синхронизации.

**Comment by 4eRTuk** [comment]
Fixed in https://github.com/nextgis/nextgisweb/commit/21194c02c8abce08eb2495c99f2c7ae2846666d3
