### ISSUE TITLE
выносится значек фотоснимка

### ISSUE THREAD

**Issue by PoohE** [nextgis/mobile.forestviolate.user#85]
При заполнении сообщения и нажатии на "сделать снимок" появляется значек фотоапарата, который становится недоступным, так как панель клавиш сдвигает экран. Нужно предусмотреть сдвигание значка или разместить его в нижнем углу

**Comment by PoohE** [comment]
может отказатся от значка? а при нажатии на меню фото переходить сразу на выбор меню?

**Comment by 4eRTuk** [comment]
@PoohE если вдруг потребуется добавить несколько фото, то мне кажется удобнее иметь значок добавления прямо в этом оверлее, а не возвращаться каждый раз к карте.
