### ISSUE TITLE
Ошибки картографических подложек

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#89]
Сообщение от тестировщика
"При отсутствии авторизации в приложении не работают карты Росреестра, «Genshtab», «OpenTopoMap». Подложка карт «ESRI Terrain» не отображает карты города Владивосток."

Так ли это? Проблема в приложении или это подложки такие? Может их убрать тогда?
@PoohE
И еще:
- "И еще нюанс. При отсутствии регистрации / авторизации никакие карты кроме гугл не подгружаются, хотя для пользователя это не очевидно."
- "На встрече с Петром Осиповым мы решили исключить карту Росеестра из приложения.
Она емкая, неповоротливая и не особо значимая. Пух не возражает."

**Comment by PoohE** [comment]
Я предлагаю оставить этот вопрос до практического использования.
Теория была в том чтобы наличием множественности подложек сделать привлекательность приложений.
Сейчас включены все подложки имеющие отображения на русской ДВ
Для неумелого пользователя есть базовая подложка которая всех устраивает

**Comment by 4eRTuk** [comment]
У Росреестра поменялся URL, я поправил в приложении.
Генштаб работает, но медленно и не на всех зумах, охват не всего мира.
OpenTopoMap перешел на SSL с неподтвержденным сертификатом.
У ESRI нет для больших зумов тайлов.

Не понял про карты гугл и авторизацию - все работает и без нее.

**Comment by BishopGIS** [comment]
Я думаю можно закрывать.
