### ISSUE TITLE
Держать ограниченное количество сообщений

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#9]
Необходимо обеспечить хранение на клиенте ограниченного количества сообщений.
При синхронизации можно запрашивать только часть данных по сообщениям пользователей (server where clause) а на клиенте удалять устаревшие данные, без передачи информации на сервер (а то на сервере удаляться).

**Comment by 4eRTuk** [comment]
Ограничение по дате создания на сколько?

**Comment by BishopGIS** [comment]
Да. Причем по идее достаточно where по дате вставить. А остальное автоматом будет - но нужно, что бы вот этот тикет был закрыт - nextgis/nextgisweb_forest_violations#18 ну и видимо вот это nextgis/nextgisweb_forest_violations#11

**Comment by 4eRTuk** [comment]
По срокам что указывать? За последний месяц?

**Comment by BishopGIS** [comment]
Пол года, но пока вот это не сделано @drnextgis nextgis/nextgisweb_forest_violations#18 ты не сможешь запросить.

**Comment by BishopGIS** [comment]
АПИ сервера готово: nextgis/nextgisweb_forest_violations#18

**Comment by 4eRTuk** [comment]
Может и для точек лесонарушений сделать?

**Comment by BishopGIS** [comment]
Да, конечно.

**Comment by BishopGIS** [comment]
@PoohE сейчас полгода стоит - на сколько поменять?

**Comment by PoohE** [comment]
можно ли этот срок выставлять в настройках самой программы?

**Comment by 4eRTuk** [comment]
@PoohE да, конечно

**Comment by 4eRTuk** [comment]
@PoohE какой-то заданный список предлагать? или ввод цифр вручную?

**Comment by PoohE** [comment]
не сохранять, месяц или полгода

**Comment by BishopGIS** [comment]
@PoohE Что значит "не сохранять" - список сообщений и карта все время пустые?

**Comment by PoohE** [comment]
не сохранять на мобильном - так можно? или минимальный срок до синхранизации

**Comment by BishopGIS** [comment]
Если оффлайн и не сохранять на мобильном, то сообщение от пользователя куда попадет?
Если стоит срок 1 день и человек ушел на неделю, то за 4 дня сообщения не будут отправлены - срок пройдет.
