### ISSUE TITLE
Добавить поддержку новых статусов

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.user#92]
См nextgis/nextgisweb_forest_violations#29
Для статуса 6 (Удален) скрывать и не показывать в списке/карте.

Для статусов отличных от https://github.com/nextgis/mobile.forestviolate.user/blob/master/app/src/main/java/com/nextgis/safeforest/util/Constants.java#L44-L47 взять какую ни будь иконку(ки).

**Comment by 4eRTuk** [comment]
@PoohE какую иконку поставить для статусов отличных от общих статусов?

**Comment by 4eRTuk** [comment]
Вот какие есть:
[Новый](https://github.com/nextgis/mobile.forestviolate.user/blob/master/app/src/main/res/drawable-xxhdpi/ic_new_mail_light.png)
[Принят в работу](https://github.com/nextgis/mobile.forestviolate.user/blob/master/app/src/main/res/drawable-xxhdpi/ic_accepted_mail_light.png)
[Проводится проверка](https://github.com/nextgis/mobile.forestviolate.user/blob/master/app/src/main/res/drawable-xxhdpi/ic_sent_mail_light.png)
[Не подтвержден](https://github.com/nextgis/mobile.forestviolate.user/blob/master/app/src/main/res/drawable-xxhdpi/ic_not_accepted_mail_light.png)
[Подтвержден](https://github.com/nextgis/mobile.forestviolate.user/blob/master/app/src/main/res/drawable-xxhdpi/ic_checked_mail_light.png)

**Comment by PoohE** [comment]
мне кажется для начала достаточно упоминания статуса в балуне точки
а к значкам вернемся, когда они станут на пром рельсы

**Comment by 4eRTuk** [comment]
Fix in f5ef0c70592a37bb8a8fc78d1147dc266223054e
